// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0N7hhUXzjRaJCeDE02S6YozUSodbV3c',
    appId: '1:374937526379:web:81868668fce55a8b3a112e',
    messagingSenderId: '374937526379',
    projectId: 'hali-app-001',
    authDomain: 'hali-app-001.firebaseapp.com',
    storageBucket: 'hali-app-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOwJnp1pf_DjA4Msb1yQYmqXoXZm0kGjY',
    appId: '1:374937526379:android:20ecebbb8a9f11053a112e',
    messagingSenderId: '374937526379',
    projectId: 'hali-app-001',
    storageBucket: 'hali-app-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3L91CDrmjTP48CPJ7wxqFfyhgkChKQUc',
    appId: '1:374937526379:ios:076292aedf3ced403a112e',
    messagingSenderId: '374937526379',
    projectId: 'hali-app-001',
    storageBucket: 'hali-app-001.firebasestorage.app',
    iosBundleId: 'com.example.hali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3L91CDrmjTP48CPJ7wxqFfyhgkChKQUc',
    appId: '1:374937526379:ios:076292aedf3ced403a112e',
    messagingSenderId: '374937526379',
    projectId: 'hali-app-001',
    storageBucket: 'hali-app-001.firebasestorage.app',
    iosBundleId: 'com.example.hali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr0N7hhUXzjRaJCeDE02S6YozUSodbV3c',
    appId: '1:374937526379:web:a9f9dfefdf48174b3a112e',
    messagingSenderId: '374937526379',
    projectId: 'hali-app-001',
    authDomain: 'hali-app-001.firebaseapp.com',
    storageBucket: 'hali-app-001.firebasestorage.app',
  );
}
